# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZmShNJsM6AOwGweaCoXtMv3Q-aIreAXL
"""



!apt update && apt install ffmpeg -y
!pip install yt-dlp
!wget -O gdrive https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive-linux-x64
!chmod +x gdrive && mv gdrive /usr/local/bin/

from google.colab import auth
auth.authenticate_user()
!gdrive list

import os
import time

# Ganti dengan username TikTok target
username = "nanakwotie"

# Path file rekaman
file_name = f"{username}_live.mp4"

print(f"🔍 Menunggu {username} live...")

while True:
    # Cek apakah user sedang live
    result = os.system(f'yt-dlp --get-title "https://www.tiktok.com/@{username}/live" > /dev/null 2>&1')

    if result == 0:  # Kalau live ditemukan
        print(f"✅ {username} sedang live! Mulai rekam...")

        # Rekam live pakai yt-dlp
        os.system(f'yt-dlp -o "{file_name}" -f best "https://www.tiktok.com/@{username}/live"')

        print("📤 Mengupload ke Google Drive...")

        # Upload ke Google Drive pakai gdrive
        os.system(f'gdrive upload "{file_name}"')

        print("✅ Upload selesai! Menghapus file lokal...")

        # Hapus file lokal setelah diupload
        os.remove(file_name)

    time.sleep(20)

"""# New Section"""